[package]
name = "snarkos-node-env"
version = "2.1.4"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Execution environment information for snarkOS"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography", "operating-systems" ]
license = "Apache-2.0"
edition = "2021"

[dependencies.once_cell]
version = "1"

[dependencies.serde]
version = "1"
features = [ "derive" ]
